### ISSUE TITLE
Hello, please add a description in English how to use your plugin

### ISSUE THREAD

**Issue by Amaratsu** [metaworking/channeld-ue-plugin#18]
Hello, please add a description in English how to use your plugin

**Comment by indiest** [comment]
Hi! There’s a plan to translate the Chinese [getting-started doc](https://github.com/metaworking/channeld-ue-plugin/blob/master/Docs/zh/installation.md) into English. Stay tuned :)

**Comment by indiest** [comment]
Finished with #35
