### ISSUE TITLE
Some rep actors cannot be updated to the cache

### ISSUE THREAD

**Issue by Augkit** [metaworking/channeld-ue-plugin#24]
![WeChat Image_20230519184803](https://github.com/metaworking/channeld-ue-plugin/assets/23498912/43543fe8-297a-4cfc-8f19-1558a2e96ff2)
The BP_RepGameState is a rep actor, but there is no way to add him as a state to the channeld data schema. Similarly, ReplicationfActor Cache.json doesn't include it.

**Comment by indiest** [comment]
Deleting `Intermediate` and then re-building the project can fix this issue.

If we don't plan to fix the code, alternatively we should include the workaround in the docs (maybe in Troubleshootings).

**Comment by indiest** [comment]
Fixed in 28ff7bd9a846f9d5e38b4e09bbac051caa64debe and 865fa9a4603a8401f3e4a18e9e9da1a9f6edeb76
