### ISSUE TITLE
Components that do not have replication enabled are also forced to depend

### ISSUE THREAD

**Issue by Augkit** [metaworking/channeld-ue-plugin#25]
![WeChat Image_20230520092616](https://github.com/metaworking/channeld-ue-plugin/assets/23498912/7d128a16-1fcf-4d82-99d5-89300ce79de5)
I didn't turn on replication for BP_TestNPC's static mesh, but the schema editor still shows a dependency on static mesh

**Comment by indiest** [comment]
Any replicated ActorComponent (has replicated property or RPC) will have its corresponding state generated in the replication cache.

If a replicated Actor(B) owns a replicated ActorComponent(AC) directly, adding the actor's state will also add the ActorComponent's state (this is what we called "dependency"); if AC is owned by actor A which is the parent class of B, and A is not a replicated Actor, there will be no dependency as  A's state doesn't exist.
