### ISSUE TITLE
There is a lack of documentation regarding the usage of ChanneldCharacter and ChanneldMovementComponent.

### ISSUE THREAD

**Issue by laughxing** [metaworking/channeld-ue-plugin#52]
The documentation does not mention the usage of ChanneldCharacter and ChanneldMovementComponent. As a result, if a user is unaware of this, they may encounter a crash when testing the spatial data view. This can be confusing and difficult to identify the cause of.

**Comment by indiest** [comment]
Thanks for the feedback! These custom classes will be introduced and guided in the Getting Started docs.

**Comment by indiest** [comment]
Fixed in 3fe90c1a8e6974c5b8356cea65c8f1bea2b3b762
