### ISSUE TITLE
Performance Stress

### ISSUE THREAD

**Issue by khalid-huang** [metaworking/channeld-ue-plugin#53]
I plan to conduct a performance stress test on the channeld UE plugins to see how many client connections can be supported. Has anyone done similar work before and would like to discuss it? How to conduct effective and reasonable testing, and what are the test results

**Comment by indiest** [comment]
There's a couple of maps in the [demos project](../../channeld-ue-demos) can be usd for stress test:
- `TestReplication` for single game server
- `TestSpatial_Benchmark` for multiple game servers

You can also use the files in the `Package` folder to perform docker-based test (one container per game client).

Please note that the test results depend on what scenario you build. In my case, I had 100 simulated clients keep moving and jumping in 9 spatial servers, and the CPU usage of channeld was about 100%-150%. It was an unrepresentive case though, as no player is moving all the times in the real world.

**Comment by indiest** [comment]
https://www.channeld.org/#/benchmark
