### ISSUE TITLE
[BUG]  A Batch of Clients Disconnect

### ISSUE THREAD

**Issue by khalid-huang** [metaworking/channeld-ue-plugin#54]
**What happened**:
I am doing Performance Stress Test https://github.com/metaworking/channeld-ue-plugin/issues/53, but often encounter situations where a batch of clients disconnect. 
The following is the error log of the ue client
```
LogChanneld: Error: Failed to send packet to channld, msgTypes: 102, 102,, send/full size: -1/134, last packet size: 129. 
logNet: UNetDriver::TickDispatch: Very log time between tick. DeltaTime: 0.03, Realtime: 19.72, channeldNetDriver_2147482580
```
![image](https://github.com/metaworking/channeld-ue-plugin/assets/13484086/d9f1ecb3-2829-4c0b-bfc7-b5913d4d88de)

The following is the error log of the ue server
```
LogChanneld: Error: Failed to send packet to channld, msgTypes: 8, , send/full size: -1/68, last packet size: 63. 
LogChanneld: Error: Failed to send packet to channld, msgTypes: 8, , send/full size: -1/68, last packet size: 63. 
LogChanneld: Error: Failed to send packet to channld, msgTypes: 8, , send/full size: -1/68, last packet size: 63. 
LogChanneld: Error: Failed to send packet to channld, msgTypes: 8, , send/full size: -1/68, last packet size: 63. 
```
![image](https://github.com/metaworking/channeld-ue-plugin/assets/13484086/94044979-1233-4470-bfec-8f4c9d22f2e1)

The following is the error log of the channld service
```
WARN channld/channel.go:384 spend too long handling messages, will delay the left to the next tick {"channelType:" "GOBAL", "channeld:" 0, "duration":"20.6272ms“, remaining: "111"}
WARN channld/channel.go:384 spend too long handling messages, will delay the left to the next tick {"channelType:" "GOBAL", "channeld:" 0, "duration":"20.6272ms“, remaining: "879"}
WARN channld/channel.go:384 spend too long handling messages, will delay the left to the next tick {"channelType:" "GOBAL", "channeld:" 0, "duration":"20.6272ms“, remaining: "448"}
WARN channld/channel.go:607  packet is going to be oversized {"connType": "SERVER", "connId": 1, "packetSize":65584, "msgType":102, msgSize": 49, "msgNum"1107, "msgInQueue": 128}
```

My deployment topology is following the architecture of https://github.com/metaworking/channeld/blob/release/doc/architecture.png

I run multiple ue clients on one virtual machine 01(windows) , one ue server on virtual machine 02(windows), and the channld service run on virtual machine 03(windows)

**What you expected to happen**:
I hope the clients can stay connected without disconnection, otherwise I cannot conduct the testing

**Environment**:
- Channld version: 0.6.0
- Channld-UE Plugin version: 0.6.0

**Comment by indiest** [comment]
Hi, @khalid-huang, thanks for the bug report! There are a couple of quesions I'd like to follow up:
- What's the setup of your test scenario (e.g. which map and view you are using)?
- Has any of the game clients successfully entered the online game?
- Are the three virtual machines running on the same physical machine?

**Comment by khalid-huang** [comment]
**Has any of the game clients successfully entered the online game?**
yes, we have a client for observation purposes (without nullrhi), and we can see many other clients(more than 100). Howerver, during the adding other client or other situation, the situation decribed above occurs.

**Are the three virtual machines running on the same physical machine?**
I do not think so. We directly pruchased virtual machine resources on the cloud.

**Comment by indiest** [comment]
It seems that you were trying to run 171 clients in one channel/server, and channeld hit the bottleneck because:
1. A channel is running on one goroutine. Too many channel data updates had saturated the message queue;
2. 171 clients that replicate each other's movement is not an ideal scenario for online games. It takes too much outgoing bandwidth of the server. Let's say a player character's movement update has 20 bytes in size. A client needs 20 bytes * 30 fps * 170 other player ~= 100KB/s, and channeld needs 100KB/s * 171 = 17.4MB/s bandwidth to handle all the replication.

To validate the CPU and network stats, you can use the Grafana dashboard in your deployement.

If you are targeting more CCU in your stress test, I would suggest to split the clients into multiple spatial channels.
