### ISSUE TITLE
UE5版本WorldPartition地图，无法使用插件

### ISSUE THREAD

**Issue by Lee97** [metaworking/channeld-ue-plugin#87]
WorldPartition地图中，如果没有添加PlayerStart ，地图无法生成pawn；如果添加了PlayerStart，地图中会生成pawn，但无法控制。

![QQ图片20231204160616](https://github.com/metaworking/channeld-ue-plugin/assets/40079568/1a71aae2-3eef-42d0-8792-54a0f2aa7fd0)
![QQ图片20231204160625](https://github.com/metaworking/channeld-ue-plugin/assets/40079568/66e40ec8-5512-4051-87ff-ad617ad9bd01)

**Comment by Lee97** [comment]
在dubug过程中发现  ChanneldUtils::GetObjectByRef 方法没有生成 PlayerController （BP_TestSpatialPC）
方法中 UPackageMapClient::SerializeNewActor 函数返回false
![image](https://github.com/metaworking/channeld-ue-plugin/assets/40079568/deb5adf3-f72d-4039-8fd9-1fd5037aaae5)

继续追UPackageMapClient::SerializeNewActor 方法，当为wp地图，创建 PlayerController （BP_TestSpatialPC）时，NetGUID为单数
![image](https://github.com/metaworking/channeld-ue-plugin/assets/40079568/fba25e44-7748-40bd-810c-6addf05cf38f)

所以此方法没有执行
![image](https://github.com/metaworking/channeld-ue-plugin/assets/40079568/cd674d1b-6412-4388-a517-95b42973c458)

**Comment by indiest** [comment]
Fixed in v0.7.2 release
